services:
  - type: web
    name: sql-data-agent
    env: node
    plan: free
    region: oregon
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false

      - key: VITE_FIREBASE_API_KEY
        value: AIzaSyC9OxDlPH9kz05bobAAk1RJM1cuOau-GSo
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: retail-store-sql-agent.firebaseapp.com
      - key: VITE_FIREBASE_PROJECT_ID
        value: retail-store-sql-agent
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: retail-store-sql-agent.firebasestorage.app
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        value: "226451810068"
      - key: VITE_FIREBASE_APP_ID
        value: 1:226451810068:web:c7a15385d4761278384401
